/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testesDosBotoes;

import jopAlternativo.JopAlternativo;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harisson.castro
 */
public class JopAndButtons extends javax.swing.JFrame {

    JopAlternativo jopAlternativo = new JopAlternativo();

    /**
     * Creates new form JopAndButtons
     */
    public JopAndButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTesteDoJop = new javax.swing.JButton();
        lbResultadoDoJop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTesteDoJop.setBackground(new java.awt.Color(0, 0, 0));
        lbTesteDoJop.setForeground(new java.awt.Color(255, 255, 255));
        lbTesteDoJop.setText("Teste do jopAlternativo");
        lbTesteDoJop.setBorderPainted(false);
        lbTesteDoJop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTesteDoJop.setFocusPainted(false);
        lbTesteDoJop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTesteDoJopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTesteDoJopMouseExited(evt);
            }
        });
        lbTesteDoJop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTesteDoJopActionPerformed(evt);
            }
        });

        lbResultadoDoJop.setText("resultado do jop");
        lbResultadoDoJop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbResultadoDoJopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTesteDoJop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultadoDoJop)
                .addGap(0, 385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbResultadoDoJop)
                    .addComponent(lbTesteDoJop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 334, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbTesteDoJopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTesteDoJopMouseExited
        lbTesteDoJop.setBackground(Color.BLACK);
        lbTesteDoJop.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbTesteDoJopMouseExited

    private void lbTesteDoJopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTesteDoJopMouseEntered
        lbTesteDoJop.setBackground(Color.WHITE);
        lbTesteDoJop.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbTesteDoJopMouseEntered

    private void lbTesteDoJopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTesteDoJopActionPerformed
        jopAlternativoThread();
    }//GEN-LAST:event_lbTesteDoJopActionPerformed

    private void lbResultadoDoJopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbResultadoDoJopActionPerformed
        JOptionPane.showMessageDialog(null, jopAlternativo.getNumero());
    }//GEN-LAST:event_lbResultadoDoJopActionPerformed
    private void jopAlternativoThread() {
        jopAlternativo.setVisible(true);
        new Thread() {
            @Override
            public void run() {
                while (jopAlternativo.isVisible()) {
                    desabilitadorDeBotoes(false);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
                desabilitadorDeBotoes(true);
                resultadoDoJopAlternativo();
            }
        }.start();

    }

    private void resultadoDoJopAlternativo() {
        switch (jopAlternativo.getNumero()) {
            case 1:
                System.out.println(jopAlternativo.getNumero());
                break;
            case 2:
                System.out.println(jopAlternativo.getNumero());
                break;
            case 3:
                System.out.println(jopAlternativo.getNumero());
                break;
            case 4:
                System.out.println(jopAlternativo.getNumero());
                break;
        }
    }

    private void desabilitadorDeBotoes(boolean estado) {
        lbTesteDoJop.setEnabled(estado);
        lbResultadoDoJop.setEnabled(estado);
    }
//
//    public Icon icone(String path, int width, int height) {
//        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
//                .getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
//
//        return img;

    //STRING PATH
    //path nada mais é que o local que a arquivo/pasta está alocado
    //INT WIDTH & INT HEIGHT
    //os dois nada mais são do que Largura e Altura.
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JopAndButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JopAndButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JopAndButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JopAndButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JopAndButtons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lbResultadoDoJop;
    private javax.swing.JButton lbTesteDoJop;
    // End of variables declaration//GEN-END:variables
}
